Support pulling OCI Image Index manifests
GoogleContainerTools/jib pull request #3715
Opened 2022-07-28 20:59 UTC by rquinio

Resolves #2749

Implementation follows https://github.com/GoogleContainerTools/jib/issues/3700#issuecomment-1171283502

- Add Accept header application/vnd.oci.image.index.v1+json during base image pull
- Re-use the logic from V22ManifestListTemplate to select the target platform diget via a new interface ManifestListTemplate

Before filing a pull request, make sure to do the following:

- [x] Create a new issue at https://github.com/GoogleContainerTools/jib/issues/new/choose.
- [x] Ensure that your implementation plan is approved by the team.
- [x] Verify that integration tests and unit tests are passing after the change.
- [x] Address all checkstyle issues. Refer to the [style guide](https://github.com/GoogleContainerTools/jib/blob/0ed7dca36864b6b19ff61629fc578018041fa15f/STYLE_GUIDE.md#style-guide).

This helps to reduce the chance of having a pull request rejected.

2022-07-29 21:44 UTC, elefeint commented
@rquinio Thank you; we'll review next week.

2022-08-12 22:49 UTC, elefeint requested changes
The PR looks very good; I apologize for the delay.

Could you run `./gradlew goJF` to reformat the code ([details](https://github.com/GoogleContainerTools/jib/blob/0ed7dca36864b6b19ff61629fc578018041fa15f/STYLE_GUIDE.md#automatic-formatting)? That should fix the code coverage by allowing tests to run.

2022-08-12 22:49 UTC, elefeint commented on jib-core/src/main/java/com/google/cloud/tools/jib/image/json/ManifestListTemplate.java
> + * Copyright 2017 Google LLC.
2022

2022-08-13 10:37 UTC, rquinio commented on jib-core/src/main/java/com/google/cloud/tools/jib/image/json/ManifestListTemplate.java
> + * Copyright 2017 Google LLC.
Fixed

2022-08-13 11:08 UTC, rquinio commented
No worries. Hopefully I've fixed the formatting issue.

2022-08-19 20:45 UTC, elefeint requested changes
Could you add tests for:
1) `AbstractManifestPuller.getAccept()` returning the correct media type for `OciIndexTemplate.class`
2) `AbstractManifestPuller.getManifestTemplateFromJson() returning the right thing

Thank you!

2022-08-20 12:44 UTC, rquinio commented
Done ! I also took the opportunity to fix missing coverage in PullBaseImageStep for manifest lists pulling and case where the target architecture is not in the list.

2022-08-23 14:35 UTC, elefeint commented
Test failure:
```
> Task :jib-core:test

com.google.cloud.tools.jib.builder.steps.PullBaseImageStepTest > testCall_allMirrorsFail FAILED
    java.lang.NullPointerException
        at com.google.cloud.tools.jib.builder.steps.PullBaseImageStep.pullBaseImages(PullBaseImageStep.java:296)
        at com.google.cloud.tools.jib.builder.steps.PullBaseImageStep.call(PullBaseImageStep.java:159)
        at com.google.cloud.tools.jib.builder.steps.PullBaseImageStepTest.testCall_allMirrorsFail(PullBaseImageStepTest.java:571)

com.google.cloud.tools.jib.builder.steps.PullBaseImageStepTest STANDARD_OUT
    [MockitoHint] PullBaseImageStepTest.testCall_allMirrorsFail (see javadoc for MockitoHint):
    [MockitoHint] 1. Unused... -> at com.google.cloud.tools.jib.builder.steps.PullBaseImageStepTest.setUpWorkingRegistryClientFactoryWithV22ManifestList(PullBaseImageStepTest.java:672)
    [MockitoHint]  ...args ok? -> at com.google.cloud.tools.jib.builder.steps.PullBaseImageStep.pullBaseImages(PullBaseImageStep.java:294)
```

2022-08-23 20:58 UTC, rquinio commented
Should be fixed, testCall_allMirrorsFail was wrongly using the client factory with new V22ManifestList mocks, instead of the old V22ManifestTeplate mock.

2022-08-23 22:07 UTC, elefeint commented
@rquinio Thank you! I'm afraid we need a bit more testing to pass the 80% coverage gate. `OciIndexTemplate.ManifestDescriptorTemplate` is likely an easy candidate. Can you see the Sonar report that's linked in "Details" under the Github Action checks?

2022-08-24 20:23 UTC, rquinio commented
@elefeint I've added a test for POJO -> JSON serialization.
I had a look at the code duplication, but I wouldn't risk factorizing the JSON objects between docker and OCI manifests as they have different fields, and I'm not sure of the details of each spec.

2022-08-25 16:15 UTC, elefeint approved these changes
Thanks! I agree that the two formats could easily diverge in the future.

2022-08-25 16:46 UTC, merged